# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SzcAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(verbose_name='add\u5e8f\u53f7ID')),
                ('address_linkman', models.CharField(max_length=5)),
                ('address_linktel', models.CharField(blank=True, max_length=11, null=True)),
                ('address_detail', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('isdefault', models.IntegerField()),
            ],
            options={
                'verbose_name': '\u5730\u5740',
                'db_table': 'szc_addr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('typeid', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'szc_banners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcBannerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_banner_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcCarousel',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('valid', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_carousel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcChefs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('photo', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('styleid', models.IntegerField()),
                ('monicker', models.CharField(max_length=100)),
                ('grade', models.FloatField()),
                ('vedio', models.CharField(max_length=255)),
                ('supporter', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_chefs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcCoupons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('uid', models.IntegerField()),
                ('value', models.FloatField()),
                ('min', models.FloatField()),
                ('valid_date', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcDishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('img', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('en', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('chef_id', models.IntegerField()),
                ('favors', models.IntegerField()),
                ('price', models.FloatField()),
                ('vedio', models.CharField(max_length=255)),
                ('recommended', models.IntegerField()),
                ('status', models.IntegerField()),
                ('num', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('vipprice', models.FloatField()),
                ('type', models.IntegerField()),
                ('style', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_dishes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcDishTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('title', models.CharField(max_length=20)),
                ('benable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_dish_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('name', models.CharField(max_length=50)),
                ('lower', models.CharField(max_length=2000)),
                ('status', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'szc_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcMemberAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'szc_member_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=20)),
                ('addr_id', models.IntegerField()),
                ('balance', models.FloatField()),
                ('last_ip', models.CharField(max_length=255)),
                ('last_time', models.IntegerField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('active', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('iconfont', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'szc_module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_id', models.IntegerField()),
                ('dish_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u8ba2\u5355id')),
                ('sn', models.CharField(max_length=17)),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('tel', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('addr', models.CharField(max_length=255)),
                ('addrid', models.IntegerField(blank=True, null=True)),
                ('couponid', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('paied', models.FloatField()),
                ('order_time', models.IntegerField()),
                ('pay_time', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('pay_channel', models.CharField(blank=True, choices=[('wx', '\u5fae\u4fe1'), ('alipay', '\u652f\u4ed8\u5b9d'), ('yue', '\u4f59\u989d'), ('', '\u672a\u77e5')], max_length=10, null=True, verbose_name='\u652f\u4ed8\u6e20\u9053')),
                ('isnew', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, '\u5df2\u652f\u4ed8'), (2, '\u5df2\u9000\u6b3e'), (0, '\u5f85\u652f\u4ed8')], default=0, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('note', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=12, null=True)),
                ('from_field', models.IntegerField(db_column='from')),
                ('order_freight', models.FloatField()),
                ('testtime', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5217\u8868',
                'db_table': 'szc_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcPowers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lower', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'szc_powers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcRechargeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('recharge_sn', models.CharField(max_length=20)),
                ('member_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('create_time', models.CharField(max_length=11)),
                ('end_time', models.CharField(max_length=11)),
                ('status', models.IntegerField()),
                ('pay_channel', models.CharField(blank=True, max_length=5, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_recharge_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcRechargeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('value', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_recharge_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcStyle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('benable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('uname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=20, null=True)),
                ('area_id', models.CharField(blank=True, max_length=20, null=True)),
                ('group_id', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('last_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('last_time', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'szc_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzcZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5e8f\u53f7ID')),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'szc_zone',
                'managed': False,
            },
        ),
    ]
